network:
  ecg_model: resnet18
  # ecg_model: vit_tiny
  num_leads: 1
  ### this part does not control builder/trainer
  text_model: ncbi/MedCPT-Query-Encoder
  free_layers: 6 # set 12 to freeze all layer in bert
  feature_dim: 768

  projection_head:
    mlp_hidden_size: 256
    projection_size: 256
  ###

dataset:
  dataset_name: 'mimic'
  data_path: 'your_path/' # add your image file path here

# params for trainer
trainer:
  batch_size: 128
  val_batch_size: 128
  checkpoint_interval: 50
  max_epochs: 50
  num_workers: 8

optimizer:
  params:
    lr: 1.0e-3
    weight_decay: 1.0e-8

# params for zeroshot eval
zeroshot:
  prompt_type: 'CKEPE'
  prompt_dict: '/data1/1shared/lijun/ecg/ECG-EchoReport/zeroshot/CKEPE_prompt.json'
  batch_size: 256
  num_workers: 8
  meta_data_path: '/hot_data/lijun/data/mimic-iv-ecg-diagnostic-electrocardiogram-matched-subset-1.0/'
  meta_split_path: '/data1/1shared/lijun/ecg/ECG-EchoReport/finetune/data_split/'
  
  test_sets:
    I313_I314:
      data_path: ''
      split_path: 'I313_I314.csv'

    I_num_2:
      data_path: ''
      split_path: 'I_num_2.csv'
      
  # ###
  #   ptbxl_super_class:
  #     data_path: 'ptb-xl'
  #     split_path: 'ptbxl/super_class/ptbxl_super_class_test.csv'
  # ###
  #   ptbxl_sub_class:
  #     data_path: 'ptb-xl'
  #     split_path: 'ptbxl/sub_class/ptbxl_sub_class_test.csv'
  # ###
  #   ptbxl_form:
  #     data_path: 'ptb-xl'
  #     split_path: 'ptbxl/form/ptbxl_form_test.csv'
  # ###
  #   ptbxl_rhythm:
  #     data_path: 'ptb-xl'
  #     split_path: 'ptbxl/rhythm/ptbxl_rhythm_test.csv'
  # ###
  #   icbeb:
  #     data_path: 'icbeb2018/records500'
  #     split_path: 'icbeb/icbeb_test.csv'
  # ###
  #   chapman:
  #     data_path: ''
  #     split_path: 'chapman/chapman_test.csv'


# your model name
wandb_name: '1_lead_model'