_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.2
            "6": 4.45.1
            "8":
                - 5
            "12": 0.18.2
            "13": linux-x86_64
batch_size:
    value: 128
ecg_model:
    value: resnet18
learning_rate:
    value: 0.001
prompt_type:
    value: CKEPE
text_model:
    value: ncbi/MedCPT-Query-Encoder
total_epochs:
    value: 20
val_zeroshot:
    value: all_sets
weight_decay:
    value: 1e-08
